apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure-app
  template:
    metadata:
      labels:
        app: medicure-app
    spec:
      containers:
      - name: medicure-container
        image: abhisdockerhub/medicure-app:latest  # This will be replaced in pipeline
        ports:
        - containerPort: 8082
